spring.application.name=vacaciones

spring.datasource.url=jdbc:mysql://localhost:3306/Vacaciones
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root